// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package db

import (
	"context"
	"database/sql"
)

const insertChannelAccess = `-- name: InsertChannelAccess :one
INSERT INTO channel_access
    (id, channel_id, principal_type, user_id, role_key, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, channel_id, principal_type, user_id, role_key, created_at
`

type InsertChannelAccessParams struct {
	ID            int64          `json:"id"`
	ChannelID     int64          `json:"channel_id"`
	PrincipalType string         `json:"principal_type"`
	UserID        sql.NullInt64  `json:"user_id"`
	RoleKey       sql.NullString `json:"role_key"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) InsertChannelAccess(ctx context.Context, arg InsertChannelAccessParams) (ChannelAccess, error) {
	row := q.db.QueryRowContext(ctx, insertChannelAccess,
		arg.ID,
		arg.ChannelID,
		arg.PrincipalType,
		arg.UserID,
		arg.RoleKey,
		arg.CreatedAt,
	)
	var i ChannelAccess
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PrincipalType,
		&i.UserID,
		&i.RoleKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertGroupAccess = `-- name: InsertGroupAccess :one
INSERT INTO group_access
    (id, group_id, principal_type, user_id, role_key, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, group_id, principal_type, user_id, role_key, created_at
`

type InsertGroupAccessParams struct {
	ID            int64          `json:"id"`
	GroupID       int64          `json:"group_id"`
	PrincipalType string         `json:"principal_type"`
	UserID        sql.NullInt64  `json:"user_id"`
	RoleKey       sql.NullString `json:"role_key"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) InsertGroupAccess(ctx context.Context, arg InsertGroupAccessParams) (GroupAccess, error) {
	row := q.db.QueryRowContext(ctx, insertGroupAccess,
		arg.ID,
		arg.GroupID,
		arg.PrincipalType,
		arg.UserID,
		arg.RoleKey,
		arg.CreatedAt,
	)
	var i GroupAccess
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PrincipalType,
		&i.UserID,
		&i.RoleKey,
		&i.CreatedAt,
	)
	return i, err
}

const listAllChannelAccess = `-- name: ListAllChannelAccess :many
SELECT id, channel_id, principal_type, user_id, role_key, created_at FROM channel_access ORDER BY id
`

func (q *Queries) ListAllChannelAccess(ctx context.Context) ([]ChannelAccess, error) {
	rows, err := q.db.QueryContext(ctx, listAllChannelAccess)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelAccess
	for rows.Next() {
		var i ChannelAccess
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.PrincipalType,
			&i.UserID,
			&i.RoleKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGroupAccess = `-- name: ListAllGroupAccess :many
SELECT id, group_id, principal_type, user_id, role_key, created_at FROM group_access ORDER BY id
`

func (q *Queries) ListAllGroupAccess(ctx context.Context) ([]GroupAccess, error) {
	rows, err := q.db.QueryContext(ctx, listAllGroupAccess)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupAccess
	for rows.Next() {
		var i GroupAccess
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PrincipalType,
			&i.UserID,
			&i.RoleKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelAccess = `-- name: ListChannelAccess :many
SELECT id, channel_id, principal_type, user_id, role_key, created_at FROM channel_access WHERE channel_id = ? ORDER BY id
`

func (q *Queries) ListChannelAccess(ctx context.Context, channelID int64) ([]ChannelAccess, error) {
	rows, err := q.db.QueryContext(ctx, listChannelAccess, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelAccess
	for rows.Next() {
		var i ChannelAccess
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.PrincipalType,
			&i.UserID,
			&i.RoleKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupAccess = `-- name: ListGroupAccess :many
SELECT id, group_id, principal_type, user_id, role_key, created_at FROM group_access WHERE group_id = ? ORDER BY id
`

func (q *Queries) ListGroupAccess(ctx context.Context, groupID int64) ([]GroupAccess, error) {
	rows, err := q.db.QueryContext(ctx, listGroupAccess, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupAccess
	for rows.Next() {
		var i GroupAccess
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PrincipalType,
			&i.UserID,
			&i.RoleKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
