// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"
	"database/sql"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels
    (id, group_id, name, mode, temporary, visibility, capacity, position,
     pinned, created_by, created_at, updated_at, version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
RETURNING id, group_id, name, mode, "temporary", visibility, capacity, position, pinned, created_by, created_at, updated_at, version
`

type CreateChannelParams struct {
	ID         int64         `json:"id"`
	GroupID    sql.NullInt64 `json:"group_id"`
	Name       string        `json:"name"`
	Mode       string        `json:"mode"`
	Temporary  int64         `json:"temporary"`
	Visibility string        `json:"visibility"`
	Capacity   int64         `json:"capacity"`
	Position   int64         `json:"position"`
	Pinned     int64         `json:"pinned"`
	CreatedBy  sql.NullInt64 `json:"created_by"`
	CreatedAt  int64         `json:"created_at"`
	UpdatedAt  int64         `json:"updated_at"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.Mode,
		arg.Temporary,
		arg.Visibility,
		arg.Capacity,
		arg.Position,
		arg.Pinned,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Mode,
		&i.Temporary,
		&i.Visibility,
		&i.Capacity,
		&i.Position,
		&i.Pinned,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createChannelGroup = `-- name: CreateChannelGroup :one
INSERT INTO channel_groups
    (id, name, position, visibility, created_at, updated_at, version)
VALUES (?, ?, ?, ?, ?, ?, 1)
RETURNING id, name, position, visibility, created_at, updated_at, version
`

type CreateChannelGroupParams struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Position   int64  `json:"position"`
	Visibility string `json:"visibility"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) CreateChannelGroup(ctx context.Context, arg CreateChannelGroupParams) (ChannelGroup, error) {
	row := q.db.QueryRowContext(ctx, createChannelGroup,
		arg.ID,
		arg.Name,
		arg.Position,
		arg.Visibility,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ChannelGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :one
DELETE FROM channels WHERE id = ? RETURNING id
`

func (q *Queries) DeleteChannel(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteChannel, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, group_id, name, mode, "temporary", visibility, capacity, position, pinned, created_by, created_at, updated_at, version FROM channels WHERE id = ?
`

func (q *Queries) GetChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Mode,
		&i.Temporary,
		&i.Visibility,
		&i.Capacity,
		&i.Position,
		&i.Pinned,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getChannelGroup = `-- name: GetChannelGroup :one
SELECT id, name, position, visibility, created_at, updated_at, version FROM channel_groups WHERE id = ?
`

func (q *Queries) GetChannelGroup(ctx context.Context, id int64) (ChannelGroup, error) {
	row := q.db.QueryRowContext(ctx, getChannelGroup, id)
	var i ChannelGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listChannelGroups = `-- name: ListChannelGroups :many
SELECT id, name, position, visibility, created_at, updated_at, version FROM channel_groups
ORDER BY position, created_at, id
`

func (q *Queries) ListChannelGroups(ctx context.Context) ([]ChannelGroup, error) {
	rows, err := q.db.QueryContext(ctx, listChannelGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelGroup
	for rows.Next() {
		var i ChannelGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, group_id, name, mode, "temporary", visibility, capacity, position, pinned, created_by, created_at, updated_at, version FROM channels
ORDER BY position, created_at, id
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Mode,
			&i.Temporary,
			&i.Visibility,
			&i.Capacity,
			&i.Position,
			&i.Pinned,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
