// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: configs.sql

package db

import (
	"context"
	"database/sql"
)

const deleteChannelPermissionConfig = `-- name: DeleteChannelPermissionConfig :one
DELETE FROM scope_permission_configs
WHERE scope_type = 'channel' AND channel_id = ?
RETURNING channel_id
`

func (q *Queries) DeleteChannelPermissionConfig(ctx context.Context, channelID sql.NullInt64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, deleteChannelPermissionConfig, channelID)
	var channel_id sql.NullInt64
	err := row.Scan(&channel_id)
	return channel_id, err
}

const deleteGroupPermissionConfig = `-- name: DeleteGroupPermissionConfig :one
DELETE FROM scope_permission_configs
WHERE scope_type = 'group' AND group_id = ?
RETURNING group_id
`

func (q *Queries) DeleteGroupPermissionConfig(ctx context.Context, groupID sql.NullInt64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, deleteGroupPermissionConfig, groupID)
	var group_id sql.NullInt64
	err := row.Scan(&group_id)
	return group_id, err
}

const getChannelPermissionConfig = `-- name: GetChannelPermissionConfig :one
SELECT scope_type, group_id, channel_id, config, updated_at, version FROM scope_permission_configs
WHERE scope_type = 'channel' AND channel_id = ?
`

func (q *Queries) GetChannelPermissionConfig(ctx context.Context, channelID sql.NullInt64) (ScopePermissionConfig, error) {
	row := q.db.QueryRowContext(ctx, getChannelPermissionConfig, channelID)
	var i ScopePermissionConfig
	err := row.Scan(
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.Config,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getGroupPermissionConfig = `-- name: GetGroupPermissionConfig :one
SELECT scope_type, group_id, channel_id, config, updated_at, version FROM scope_permission_configs
WHERE scope_type = 'group' AND group_id = ?
`

func (q *Queries) GetGroupPermissionConfig(ctx context.Context, groupID sql.NullInt64) (ScopePermissionConfig, error) {
	row := q.db.QueryRowContext(ctx, getGroupPermissionConfig, groupID)
	var i ScopePermissionConfig
	err := row.Scan(
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.Config,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getServerPermissionConfigRow = `-- name: GetServerPermissionConfigRow :one
SELECT scope_type, group_id, channel_id, config, updated_at, version FROM scope_permission_configs
WHERE scope_type = 'server'
`

func (q *Queries) GetServerPermissionConfigRow(ctx context.Context) (ScopePermissionConfig, error) {
	row := q.db.QueryRowContext(ctx, getServerPermissionConfigRow)
	var i ScopePermissionConfig
	err := row.Scan(
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.Config,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listPermissionConfigs = `-- name: ListPermissionConfigs :many
SELECT scope_type, group_id, channel_id, config, updated_at, version FROM scope_permission_configs
ORDER BY scope_type, group_id, channel_id
`

func (q *Queries) ListPermissionConfigs(ctx context.Context) ([]ScopePermissionConfig, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScopePermissionConfig
	for rows.Next() {
		var i ScopePermissionConfig
		if err := rows.Scan(
			&i.ScopeType,
			&i.GroupID,
			&i.ChannelID,
			&i.Config,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServerPermissionConfig = `-- name: UpdateServerPermissionConfig :one
UPDATE scope_permission_configs
SET config = ?,
    updated_at = ?,
    version = version + 1
WHERE scope_type = 'server'
RETURNING scope_type, group_id, channel_id, config, updated_at, version
`

type UpdateServerPermissionConfigParams struct {
	Config    string `json:"config"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpdateServerPermissionConfig(ctx context.Context, arg UpdateServerPermissionConfigParams) (ScopePermissionConfig, error) {
	row := q.db.QueryRowContext(ctx, updateServerPermissionConfig, arg.Config, arg.UpdatedAt)
	var i ScopePermissionConfig
	err := row.Scan(
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.Config,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const upsertChannelPermissionConfig = `-- name: UpsertChannelPermissionConfig :one
INSERT INTO scope_permission_configs
    (scope_type, channel_id, config, updated_at, version)
VALUES ('channel', ?, ?, ?, ?)
ON CONFLICT (channel_id) WHERE scope_type = 'channel' DO UPDATE SET
    config = excluded.config,
    updated_at = excluded.updated_at,
    version = excluded.version
RETURNING scope_type, group_id, channel_id, config, updated_at, version
`

type UpsertChannelPermissionConfigParams struct {
	ChannelID sql.NullInt64 `json:"channel_id"`
	Config    string        `json:"config"`
	UpdatedAt int64         `json:"updated_at"`
	Version   int64         `json:"version"`
}

func (q *Queries) UpsertChannelPermissionConfig(ctx context.Context, arg UpsertChannelPermissionConfigParams) (ScopePermissionConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertChannelPermissionConfig,
		arg.ChannelID,
		arg.Config,
		arg.UpdatedAt,
		arg.Version,
	)
	var i ScopePermissionConfig
	err := row.Scan(
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.Config,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const upsertGroupPermissionConfig = `-- name: UpsertGroupPermissionConfig :one
INSERT INTO scope_permission_configs
    (scope_type, group_id, config, updated_at, version)
VALUES ('group', ?, ?, ?, ?)
ON CONFLICT (group_id) WHERE scope_type = 'group' DO UPDATE SET
    config = excluded.config,
    updated_at = excluded.updated_at,
    version = excluded.version
RETURNING scope_type, group_id, channel_id, config, updated_at, version
`

type UpsertGroupPermissionConfigParams struct {
	GroupID   sql.NullInt64 `json:"group_id"`
	Config    string        `json:"config"`
	UpdatedAt int64         `json:"updated_at"`
	Version   int64         `json:"version"`
}

func (q *Queries) UpsertGroupPermissionConfig(ctx context.Context, arg UpsertGroupPermissionConfigParams) (ScopePermissionConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertGroupPermissionConfig,
		arg.GroupID,
		arg.Config,
		arg.UpdatedAt,
		arg.Version,
	)
	var i ScopePermissionConfig
	err := row.Scan(
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.Config,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
