// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"
	"database/sql"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE invites
SET uses_left = uses_left - 1
WHERE id = ? AND uses_left > 0 AND (expires_at IS NULL OR expires_at > CAST(?2 AS INTEGER))
RETURNING id, code_hash, role_key, uses_left, expires_at, created_by, created_at
`

type ConsumeInviteParams struct {
	ID  int64 `json:"id"`
	Now int64 `json:"now"`
}

func (q *Queries) ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, consumeInvite, arg.ID, arg.Now)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.RoleKey,
		&i.UsesLeft,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (id, code_hash, role_key, uses_left, expires_at, created_by, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, code_hash, role_key, uses_left, expires_at, created_by, created_at
`

type CreateInviteParams struct {
	ID        int64         `json:"id"`
	CodeHash  string        `json:"code_hash"`
	RoleKey   string        `json:"role_key"`
	UsesLeft  int64         `json:"uses_left"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	CreatedAt int64         `json:"created_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.ID,
		arg.CodeHash,
		arg.RoleKey,
		arg.UsesLeft,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.RoleKey,
		&i.UsesLeft,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :one
DELETE FROM invites WHERE id = ? RETURNING id
`

func (q *Queries) DeleteInvite(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteInvite, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getInviteByCodeHash = `-- name: GetInviteByCodeHash :one
SELECT id, code_hash, role_key, uses_left, expires_at, created_by, created_at FROM invites WHERE code_hash = ? AND (expires_at IS NULL OR expires_at > CAST(?2 AS INTEGER))
`

type GetInviteByCodeHashParams struct {
	CodeHash string `json:"code_hash"`
	Now      int64  `json:"now"`
}

func (q *Queries) GetInviteByCodeHash(ctx context.Context, arg GetInviteByCodeHashParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCodeHash, arg.CodeHash, arg.Now)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.RoleKey,
		&i.UsesLeft,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, code_hash, role_key, uses_left, expires_at, created_by, created_at FROM invites
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListInvitesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListInvites(ctx context.Context, arg ListInvitesParams) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.RoleKey,
			&i.UsesLeft,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
