// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"
	"database/sql"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE invites
SET uses_left = uses_left - 1
WHERE id = ? AND uses_left > 0
RETURNING id, code_hash, role, uses_left, expires_at, created_by, created_at
`

func (q *Queries) ConsumeInvite(ctx context.Context, id int64) (Invite, error) {
	row := q.db.QueryRowContext(ctx, consumeInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Role,
		&i.UsesLeft,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (id, code_hash, role, uses_left, expires_at, created_by, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, code_hash, role, uses_left, expires_at, created_by, created_at
`

type CreateInviteParams struct {
	ID        int64         `json:"id"`
	CodeHash  string        `json:"code_hash"`
	Role      string        `json:"role"`
	UsesLeft  int64         `json:"uses_left"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	CreatedAt int64         `json:"created_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.ID,
		arg.CodeHash,
		arg.Role,
		arg.UsesLeft,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Role,
		&i.UsesLeft,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = ?
`

func (q *Queries) DeleteInvite(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, id)
	return err
}

const getInviteByCodeHash = `-- name: GetInviteByCodeHash :one
SELECT id, code_hash, role, uses_left, expires_at, created_by, created_at FROM invites WHERE code_hash = ?
`

func (q *Queries) GetInviteByCodeHash(ctx context.Context, codeHash string) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCodeHash, codeHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Role,
		&i.UsesLeft,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
