// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Channel struct {
	ID         int64         `json:"id"`
	GroupID    sql.NullInt64 `json:"group_id"`
	Name       string        `json:"name"`
	Mode       string        `json:"mode"`
	Temporary  int64         `json:"temporary"`
	Visibility string        `json:"visibility"`
	Capacity   int64         `json:"capacity"`
	Position   int64         `json:"position"`
	Pinned     int64         `json:"pinned"`
	CreatedBy  sql.NullInt64 `json:"created_by"`
	CreatedAt  int64         `json:"created_at"`
	UpdatedAt  int64         `json:"updated_at"`
	Version    int64         `json:"version"`
}

type ChannelAccess struct {
	ID            int64          `json:"id"`
	ChannelID     int64          `json:"channel_id"`
	PrincipalType string         `json:"principal_type"`
	UserID        sql.NullInt64  `json:"user_id"`
	RoleKey       sql.NullString `json:"role_key"`
	CreatedAt     int64          `json:"created_at"`
}

type ChannelGroup struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Position   int64  `json:"position"`
	Visibility string `json:"visibility"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
	Version    int64  `json:"version"`
}

type GroupAccess struct {
	ID            int64          `json:"id"`
	GroupID       int64          `json:"group_id"`
	PrincipalType string         `json:"principal_type"`
	UserID        sql.NullInt64  `json:"user_id"`
	RoleKey       sql.NullString `json:"role_key"`
	CreatedAt     int64          `json:"created_at"`
}

type InstallationState struct {
	ID          int64 `json:"id"`
	Initialized int64 `json:"initialized"`
}

type Invite struct {
	ID        int64         `json:"id"`
	CodeHash  string        `json:"code_hash"`
	RoleKey   string        `json:"role_key"`
	UsesLeft  int64         `json:"uses_left"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	CreatedAt int64         `json:"created_at"`
}

type ModerationMute struct {
	ID        int64         `json:"id"`
	ScopeType string        `json:"scope_type"`
	GroupID   sql.NullInt64 `json:"group_id"`
	ChannelID sql.NullInt64 `json:"channel_id"`
	UserID    int64         `json:"user_id"`
	Kind      string        `json:"kind"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	Reason    string        `json:"reason"`
	CreatedAt int64         `json:"created_at"`
	Version   int64         `json:"version"`
}

type Object struct {
	Bucket       string `json:"bucket"`
	Name         string `json:"name"`
	ContentType  string `json:"content_type"`
	Size         int64  `json:"size"`
	OriginalName string `json:"original_name"`
	CreatedAt    int64  `json:"created_at"`
}

type Role struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
	Rank        int64  `json:"rank"`
	Builtin     int64  `json:"builtin"`
	Immutable   int64  `json:"immutable"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
	Version     int64  `json:"version"`
}

type ScopePermissionConfig struct {
	ScopeType string        `json:"scope_type"`
	GroupID   sql.NullInt64 `json:"group_id"`
	ChannelID sql.NullInt64 `json:"channel_id"`
	Config    string        `json:"config"`
	UpdatedAt int64         `json:"updated_at"`
	Version   int64         `json:"version"`
}

type Session struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	DeviceID      string         `json:"device_id"`
	TokenHash     string         `json:"token_hash"`
	PrevTokenHash sql.NullString `json:"prev_token_hash"`
	ExpiresAt     int64          `json:"expires_at"`
	LastUsedAt    int64          `json:"last_used_at"`
	CreatedAt     int64          `json:"created_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Nickname     string         `json:"nickname"`
	Avatar       sql.NullString `json:"avatar"`
	AuthVersion  int64          `json:"auth_version"`
	BannedAt     sql.NullInt64  `json:"banned_at"`
	LastLoginAt  sql.NullInt64  `json:"last_login_at"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

type UserRoleBinding struct {
	ID        int64         `json:"id"`
	UserID    int64         `json:"user_id"`
	RoleKey   string        `json:"role_key"`
	ScopeType string        `json:"scope_type"`
	GroupID   sql.NullInt64 `json:"group_id"`
	ChannelID sql.NullInt64 `json:"channel_id"`
	CreatedAt int64         `json:"created_at"`
}
