// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Invite struct {
	ID        int64         `json:"id"`
	CodeHash  string        `json:"code_hash"`
	Role      string        `json:"role"`
	UsesLeft  int64         `json:"uses_left"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	CreatedAt int64         `json:"created_at"`
}

type Session struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	DeviceID      string         `json:"device_id"`
	TokenHash     string         `json:"token_hash"`
	PrevTokenHash sql.NullString `json:"prev_token_hash"`
	ExpiresAt     int64          `json:"expires_at"`
	LastUsedAt    int64          `json:"last_used_at"`
	CreatedAt     int64          `json:"created_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Nickname     string         `json:"nickname"`
	Avatar       sql.NullString `json:"avatar"`
	AuthVersion  int64          `json:"auth_version"`
	BannedAt     sql.NullInt64  `json:"banned_at"`
	LastLoginAt  sql.NullInt64  `json:"last_login_at"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

type UserRole struct {
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}
