// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mutes.sql

package db

import (
	"context"
	"database/sql"
)

const countActiveMutes = `-- name: CountActiveMutes :one
SELECT COUNT(*) FROM moderation_mutes
WHERE expires_at IS NULL OR expires_at > ?
`

func (q *Queries) CountActiveMutes(ctx context.Context, expiresAt sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveMutes, expiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMute = `-- name: DeleteMute :one
DELETE FROM moderation_mutes WHERE id = ? RETURNING id
`

func (q *Queries) DeleteMute(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteMute, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const deleteMutesForUser = `-- name: DeleteMutesForUser :exec
DELETE FROM moderation_mutes WHERE user_id = ?
`

func (q *Queries) DeleteMutesForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMutesForUser, userID)
	return err
}

const getMute = `-- name: GetMute :one
SELECT id, scope_type, group_id, channel_id, user_id, kind, expires_at, created_by, reason, created_at, version FROM moderation_mutes WHERE id = ?
`

func (q *Queries) GetMute(ctx context.Context, id int64) (ModerationMute, error) {
	row := q.db.QueryRowContext(ctx, getMute, id)
	var i ModerationMute
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.UserID,
		&i.Kind,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const insertMute = `-- name: InsertMute :one
INSERT INTO moderation_mutes
    (id, scope_type, group_id, channel_id, user_id, kind, expires_at,
     created_by, reason, created_at, version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
RETURNING id, scope_type, group_id, channel_id, user_id, kind, expires_at, created_by, reason, created_at, version
`

type InsertMuteParams struct {
	ID        int64         `json:"id"`
	ScopeType string        `json:"scope_type"`
	GroupID   sql.NullInt64 `json:"group_id"`
	ChannelID sql.NullInt64 `json:"channel_id"`
	UserID    int64         `json:"user_id"`
	Kind      string        `json:"kind"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	Reason    string        `json:"reason"`
	CreatedAt int64         `json:"created_at"`
}

func (q *Queries) InsertMute(ctx context.Context, arg InsertMuteParams) (ModerationMute, error) {
	row := q.db.QueryRowContext(ctx, insertMute,
		arg.ID,
		arg.ScopeType,
		arg.GroupID,
		arg.ChannelID,
		arg.UserID,
		arg.Kind,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.Reason,
		arg.CreatedAt,
	)
	var i ModerationMute
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.UserID,
		&i.Kind,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const listAllMutes = `-- name: ListAllMutes :many
SELECT id, scope_type, group_id, channel_id, user_id, kind, expires_at, created_by, reason, created_at, version FROM moderation_mutes ORDER BY id
`

func (q *Queries) ListAllMutes(ctx context.Context) ([]ModerationMute, error) {
	rows, err := q.db.QueryContext(ctx, listAllMutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationMute
	for rows.Next() {
		var i ModerationMute
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.GroupID,
			&i.ChannelID,
			&i.UserID,
			&i.Kind,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.Reason,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMutesForUser = `-- name: ListMutesForUser :many
SELECT id, scope_type, group_id, channel_id, user_id, kind, expires_at, created_by, reason, created_at, version FROM moderation_mutes WHERE user_id = ? ORDER BY id
`

func (q *Queries) ListMutesForUser(ctx context.Context, userID int64) ([]ModerationMute, error) {
	rows, err := q.db.QueryContext(ctx, listMutesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationMute
	for rows.Next() {
		var i ModerationMute
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.GroupID,
			&i.ChannelID,
			&i.UserID,
			&i.Kind,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.Reason,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMute = `-- name: UpdateMute :one
UPDATE moderation_mutes
SET expires_at = ?,
    reason = ?,
    version = version + 1
WHERE id = ?
RETURNING id, scope_type, group_id, channel_id, user_id, kind, expires_at, created_by, reason, created_at, version
`

type UpdateMuteParams struct {
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	Reason    string        `json:"reason"`
	ID        int64         `json:"id"`
}

func (q *Queries) UpdateMute(ctx context.Context, arg UpdateMuteParams) (ModerationMute, error) {
	row := q.db.QueryRowContext(ctx, updateMute, arg.ExpiresAt, arg.Reason, arg.ID)
	var i ModerationMute
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.UserID,
		&i.Kind,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}
