// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: objects.sql

package db

import (
	"context"
)

const deleteObject = `-- name: DeleteObject :exec
DELETE FROM objects WHERE bucket = ? AND name = ?
`

type DeleteObjectParams struct {
	Bucket string `json:"bucket"`
	Name   string `json:"name"`
}

func (q *Queries) DeleteObject(ctx context.Context, arg DeleteObjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteObject, arg.Bucket, arg.Name)
	return err
}

const getObject = `-- name: GetObject :one
SELECT bucket, name, content_type, size, original_name, created_at FROM objects WHERE bucket = ? AND name = ?
`

type GetObjectParams struct {
	Bucket string `json:"bucket"`
	Name   string `json:"name"`
}

func (q *Queries) GetObject(ctx context.Context, arg GetObjectParams) (Object, error) {
	row := q.db.QueryRowContext(ctx, getObject, arg.Bucket, arg.Name)
	var i Object
	err := row.Scan(
		&i.Bucket,
		&i.Name,
		&i.ContentType,
		&i.Size,
		&i.OriginalName,
		&i.CreatedAt,
	)
	return i, err
}

const upsertObject = `-- name: UpsertObject :one
INSERT INTO objects (bucket, name, content_type, size, original_name, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (bucket, name) DO UPDATE SET
    content_type  = excluded.content_type,
    size          = excluded.size,
    original_name = excluded.original_name,
    created_at    = excluded.created_at
RETURNING bucket, name, content_type, size, original_name, created_at
`

type UpsertObjectParams struct {
	Bucket       string `json:"bucket"`
	Name         string `json:"name"`
	ContentType  string `json:"content_type"`
	Size         int64  `json:"size"`
	OriginalName string `json:"original_name"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) UpsertObject(ctx context.Context, arg UpsertObjectParams) (Object, error) {
	row := q.db.QueryRowContext(ctx, upsertObject,
		arg.Bucket,
		arg.Name,
		arg.ContentType,
		arg.Size,
		arg.OriginalName,
		arg.CreatedAt,
	)
	var i Object
	err := row.Scan(
		&i.Bucket,
		&i.Name,
		&i.ContentType,
		&i.Size,
		&i.OriginalName,
		&i.CreatedAt,
	)
	return i, err
}
