// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	BumpUserAuthVersion(ctx context.Context, arg BumpUserAuthVersionParams) error
	ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) (Invite, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error)
	DeleteInvite(ctx context.Context, id int64) (int64, error)
	DeleteObject(ctx context.Context, arg DeleteObjectParams) error
	DeleteSession(ctx context.Context, id int64) error
	DeleteSessionByPrevTokenHash(ctx context.Context, prevTokenHash sql.NullString) (int64, error)
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteUser(ctx context.Context, id int64) (int64, error)
	DeleteUserRoles(ctx context.Context, userID int64) error
	DeleteUserSessions(ctx context.Context, userID int64) error
	ExistsAdminRole(ctx context.Context) (bool, error)
	GetInviteByCodeHash(ctx context.Context, arg GetInviteByCodeHashParams) (Invite, error)
	GetObject(ctx context.Context, arg GetObjectParams) (Object, error)
	GetRolesForUser(ctx context.Context, userID int64) ([]string, error)
	GetSessionByID(ctx context.Context, id int64) (Session, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error
	ListInvites(ctx context.Context, arg ListInvitesParams) ([]Invite, error)
	ListSessionsByUser(ctx context.Context, userID int64) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error)
	SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) (User, error)
	SetUserBanned(ctx context.Context, arg SetUserBannedParams) error
	SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error
	TouchUserLastLogin(ctx context.Context, arg TouchUserLastLoginParams) error
	UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) (User, error)
	UpsertObject(ctx context.Context, arg UpsertObjectParams) (Object, error)
	UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
