// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"
	"database/sql"
)

const countOwners = `-- name: CountOwners :one
SELECT COUNT(*) AS count FROM user_role_bindings WHERE role_key = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwners)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoleReferences = `-- name: CountRoleReferences :one
WITH target(key) AS (SELECT CAST(?1 AS TEXT))
SELECT
    (SELECT COUNT(*) FROM user_role_bindings WHERE role_key = (SELECT key FROM target)) +
    (SELECT COUNT(*) FROM group_access WHERE role_key = (SELECT key FROM target)) +
    (SELECT COUNT(*) FROM channel_access WHERE role_key = (SELECT key FROM target)) +
    (SELECT COUNT(*) FROM invites WHERE role_key = (SELECT key FROM target)) +
    (SELECT COUNT(*) FROM scope_permission_configs, json_each(config)
     WHERE json_each.key = (SELECT key FROM target)) AS count
`

func (q *Queries) CountRoleReferences(ctx context.Context, roleKey string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoleReferences, roleKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles
    (key, display_name, rank, builtin, immutable, created_at, updated_at, version)
VALUES (?, ?, ?, 0, 0, ?, ?, 1)
RETURNING "key", display_name, rank, builtin, immutable, created_at, updated_at, version
`

type CreateRoleParams struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
	Rank        int64  `json:"rank"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole,
		arg.Key,
		arg.DisplayName,
		arg.Rank,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Role
	err := row.Scan(
		&i.Key,
		&i.DisplayName,
		&i.Rank,
		&i.Builtin,
		&i.Immutable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :one
DELETE FROM roles WHERE key = ? RETURNING key
`

func (q *Queries) DeleteRole(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteRole, key)
	var key_2 string
	err := row.Scan(&key_2)
	return key_2, err
}

const deleteRoleBinding = `-- name: DeleteRoleBinding :one
DELETE FROM user_role_bindings WHERE id = ? RETURNING id
`

func (q *Queries) DeleteRoleBinding(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteRoleBinding, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const deleteServerRoleBindingsForUser = `-- name: DeleteServerRoleBindingsForUser :exec
DELETE FROM user_role_bindings WHERE user_id = ? AND scope_type = 'server'
`

func (q *Queries) DeleteServerRoleBindingsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteServerRoleBindingsForUser, userID)
	return err
}

const getInstallationState = `-- name: GetInstallationState :one
SELECT id, installation_id, initialized FROM installation_state WHERE id = 1
`

func (q *Queries) GetInstallationState(ctx context.Context) (InstallationState, error) {
	row := q.db.QueryRowContext(ctx, getInstallationState)
	var i InstallationState
	err := row.Scan(&i.ID, &i.InstallationID, &i.Initialized)
	return i, err
}

const getOwnerBinding = `-- name: GetOwnerBinding :one
SELECT id, user_id, role_key, scope_type, group_id, channel_id, created_at FROM user_role_bindings WHERE role_key = 'owner'
`

func (q *Queries) GetOwnerBinding(ctx context.Context) (UserRoleBinding, error) {
	row := q.db.QueryRowContext(ctx, getOwnerBinding)
	var i UserRoleBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleKey,
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleBindingByID = `-- name: GetRoleBindingByID :one
SELECT id, user_id, role_key, scope_type, group_id, channel_id, created_at FROM user_role_bindings WHERE id = ?
`

func (q *Queries) GetRoleBindingByID(ctx context.Context, id int64) (UserRoleBinding, error) {
	row := q.db.QueryRowContext(ctx, getRoleBindingByID, id)
	var i UserRoleBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleKey,
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByKey = `-- name: GetRoleByKey :one
SELECT "key", display_name, rank, builtin, immutable, created_at, updated_at, version FROM roles WHERE key = ?
`

func (q *Queries) GetRoleByKey(ctx context.Context, key string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByKey, key)
	var i Role
	err := row.Scan(
		&i.Key,
		&i.DisplayName,
		&i.Rank,
		&i.Builtin,
		&i.Immutable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getServerPermissionConfig = `-- name: GetServerPermissionConfig :one
SELECT config FROM scope_permission_configs
WHERE scope_type = 'server'
`

func (q *Queries) GetServerPermissionConfig(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getServerPermissionConfig)
	var config string
	err := row.Scan(&config)
	return config, err
}

const insertRoleBinding = `-- name: InsertRoleBinding :one
INSERT INTO user_role_bindings
    (id, user_id, role_key, scope_type, group_id, channel_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, role_key, scope_type, group_id, channel_id, created_at
`

type InsertRoleBindingParams struct {
	ID        int64         `json:"id"`
	UserID    int64         `json:"user_id"`
	RoleKey   string        `json:"role_key"`
	ScopeType string        `json:"scope_type"`
	GroupID   sql.NullInt64 `json:"group_id"`
	ChannelID sql.NullInt64 `json:"channel_id"`
	CreatedAt int64         `json:"created_at"`
}

func (q *Queries) InsertRoleBinding(ctx context.Context, arg InsertRoleBindingParams) (UserRoleBinding, error) {
	row := q.db.QueryRowContext(ctx, insertRoleBinding,
		arg.ID,
		arg.UserID,
		arg.RoleKey,
		arg.ScopeType,
		arg.GroupID,
		arg.ChannelID,
		arg.CreatedAt,
	)
	var i UserRoleBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleKey,
		&i.ScopeType,
		&i.GroupID,
		&i.ChannelID,
		&i.CreatedAt,
	)
	return i, err
}

const listAllRoleBindings = `-- name: ListAllRoleBindings :many
SELECT id, user_id, role_key, scope_type, group_id, channel_id, created_at FROM user_role_bindings ORDER BY id
`

func (q *Queries) ListAllRoleBindings(ctx context.Context) ([]UserRoleBinding, error) {
	rows, err := q.db.QueryContext(ctx, listAllRoleBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRoleBinding
	for rows.Next() {
		var i UserRoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleKey,
			&i.ScopeType,
			&i.GroupID,
			&i.ChannelID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindings = `-- name: ListRoleBindings :many
SELECT id, user_id, role_key, scope_type, group_id, channel_id, created_at FROM user_role_bindings ORDER BY id LIMIT ? OFFSET ?
`

type ListRoleBindingsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListRoleBindings(ctx context.Context, arg ListRoleBindingsParams) ([]UserRoleBinding, error) {
	rows, err := q.db.QueryContext(ctx, listRoleBindings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRoleBinding
	for rows.Next() {
		var i UserRoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleKey,
			&i.ScopeType,
			&i.GroupID,
			&i.ChannelID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsForUser = `-- name: ListRoleBindingsForUser :many
SELECT id, user_id, role_key, scope_type, group_id, channel_id, created_at FROM user_role_bindings
WHERE user_id = ?
ORDER BY scope_type, group_id, channel_id, role_key
`

func (q *Queries) ListRoleBindingsForUser(ctx context.Context, userID int64) ([]UserRoleBinding, error) {
	rows, err := q.db.QueryContext(ctx, listRoleBindingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRoleBinding
	for rows.Next() {
		var i UserRoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleKey,
			&i.ScopeType,
			&i.GroupID,
			&i.ChannelID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT "key", display_name, rank, builtin, immutable, created_at, updated_at, version FROM roles ORDER BY rank DESC, display_name, key
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.Key,
			&i.DisplayName,
			&i.Rank,
			&i.Builtin,
			&i.Immutable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRoleBindings = `-- name: ListUsersWithRoleBindings :many
SELECT DISTINCT user_id FROM user_role_bindings ORDER BY user_id
`

func (q *Queries) ListUsersWithRoleBindings(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithRoleBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedInstallationState = `-- name: SeedInstallationState :execrows
INSERT OR IGNORE INTO installation_state (id, installation_id, initialized) VALUES (1, ?, 0)
`

func (q *Queries) SeedInstallationState(ctx context.Context, installationID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, seedInstallationState, installationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const seedRole = `-- name: SeedRole :exec
INSERT OR IGNORE INTO roles
    (key, display_name, rank, builtin, immutable, created_at, updated_at, version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type SeedRoleParams struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
	Rank        int64  `json:"rank"`
	Builtin     int64  `json:"builtin"`
	Immutable   int64  `json:"immutable"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
	Version     int64  `json:"version"`
}

func (q *Queries) SeedRole(ctx context.Context, arg SeedRoleParams) error {
	_, err := q.db.ExecContext(ctx, seedRole,
		arg.Key,
		arg.DisplayName,
		arg.Rank,
		arg.Builtin,
		arg.Immutable,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Version,
	)
	return err
}

const seedServerPermissionConfig = `-- name: SeedServerPermissionConfig :exec
INSERT OR IGNORE INTO scope_permission_configs
    (scope_type, config, updated_at, version)
VALUES ('server', ?, ?, 1)
`

type SeedServerPermissionConfigParams struct {
	Config    string `json:"config"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SeedServerPermissionConfig(ctx context.Context, arg SeedServerPermissionConfigParams) error {
	_, err := q.db.ExecContext(ctx, seedServerPermissionConfig, arg.Config, arg.UpdatedAt)
	return err
}

const setInstallationInitialized = `-- name: SetInstallationInitialized :execrows
UPDATE installation_state
SET initialized = ?
WHERE id = 1 AND initialized = ?
`

type SetInstallationInitializedParams struct {
	Initialized   int64 `json:"initialized"`
	Initialized_2 int64 `json:"initialized_2"`
}

func (q *Queries) SetInstallationInitialized(ctx context.Context, arg SetInstallationInitializedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setInstallationInitialized, arg.Initialized, arg.Initialized_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET display_name = ?,
    rank = ?,
    updated_at = ?,
    version = version + 1
WHERE key = ?
RETURNING "key", display_name, rank, builtin, immutable, created_at, updated_at, version
`

type UpdateRoleParams struct {
	DisplayName string `json:"display_name"`
	Rank        int64  `json:"rank"`
	UpdatedAt   int64  `json:"updated_at"`
	Key         string `json:"key"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole,
		arg.DisplayName,
		arg.Rank,
		arg.UpdatedAt,
		arg.Key,
	)
	var i Role
	err := row.Scan(
		&i.Key,
		&i.DisplayName,
		&i.Rank,
		&i.Builtin,
		&i.Immutable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
