// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionByPrevTokenHash = `-- name: DeleteSessionByPrevTokenHash :execrows
DELETE FROM sessions WHERE prev_token_hash = ?
`

func (q *Queries) DeleteSessionByPrevTokenHash(ctx context.Context, prevTokenHash sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionByPrevTokenHash, prevTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, device_id, token_hash, prev_token_hash, expires_at, last_used_at, created_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, device_id, token_hash, prev_token_hash, expires_at, last_used_at, created_at FROM sessions WHERE token_hash = ?
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, device_id, token_hash, prev_token_hash, expires_at, last_used_at, created_at FROM sessions
WHERE user_id = ?
ORDER BY last_used_at DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.TokenHash,
			&i.PrevTokenHash,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions
SET token_hash = ?1, prev_token_hash = token_hash, last_used_at = ?2, expires_at = ?3
WHERE token_hash = ?4
RETURNING id, user_id, device_id, token_hash, prev_token_hash, expires_at, last_used_at, created_at
`

type RotateSessionParams struct {
	NewTokenHash string `json:"new_token_hash"`
	LastUsedAt   int64  `json:"last_used_at"`
	ExpiresAt    int64  `json:"expires_at"`
	OldTokenHash string `json:"old_token_hash"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, rotateSession,
		arg.NewTokenHash,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.OldTokenHash,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO sessions (id, user_id, device_id, token_hash, prev_token_hash, expires_at, last_used_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id, device_id) DO UPDATE SET
    token_hash = excluded.token_hash,
    prev_token_hash = sessions.token_hash,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
RETURNING id, user_id, device_id, token_hash, prev_token_hash, expires_at, last_used_at, created_at
`

type UpsertSessionParams struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	DeviceID      string         `json:"device_id"`
	TokenHash     string         `json:"token_hash"`
	PrevTokenHash sql.NullString `json:"prev_token_hash"`
	ExpiresAt     int64          `json:"expires_at"`
	LastUsedAt    int64          `json:"last_used_at"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, upsertSession,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.TokenHash,
		arg.PrevTokenHash,
		arg.ExpiresAt,
		arg.LastUsedAt,
		arg.CreatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.PrevTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}
