// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const bumpUserAuthVersion = `-- name: BumpUserAuthVersion :exec
UPDATE users
SET auth_version = auth_version + 1, updated_at = ?
WHERE id = ?
`

type BumpUserAuthVersionParams struct {
	UpdatedAt int64 `json:"updated_at"`
	ID        int64 `json:"id"`
}

func (q *Queries) BumpUserAuthVersion(ctx context.Context, arg BumpUserAuthVersionParams) error {
	_, err := q.db.ExecContext(ctx, bumpUserAuthVersion, arg.UpdatedAt, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, password_hash, nickname, avatar, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, username, password_hash, nickname, avatar, auth_version, banned_at, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Nickname     string         `json:"nickname"`
	Avatar       sql.NullString `json:"avatar"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Nickname,
		arg.Avatar,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.AuthVersion,
		&i.BannedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users WHERE id = ? RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles WHERE user_id = ?
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserRoles, userID)
	return err
}

const existsAdminRole = `-- name: ExistsAdminRole :one
SELECT EXISTS(SELECT 1 FROM user_roles WHERE role = 'admin') AS has_admin
`

func (q *Queries) ExistsAdminRole(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsAdminRole)
	var has_admin bool
	err := row.Scan(&has_admin)
	return has_admin, err
}

const getRolesForUser = `-- name: GetRolesForUser :many
SELECT role FROM user_roles WHERE user_id = ?
`

func (q *Queries) GetRolesForUser(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, nickname, avatar, auth_version, banned_at, last_login_at, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.AuthVersion,
		&i.BannedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, nickname, avatar, auth_version, banned_at, last_login_at, created_at, updated_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.AuthVersion,
		&i.BannedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserRole = `-- name: InsertUserRole :exec
INSERT INTO user_roles (user_id, role) VALUES (?, ?)
`

type InsertUserRoleParams struct {
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, insertUserRole, arg.UserID, arg.Role)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, nickname, avatar, auth_version, banned_at, last_login_at, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Nickname,
			&i.Avatar,
			&i.AuthVersion,
			&i.BannedAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAvatar = `-- name: SetUserAvatar :one
UPDATE users
SET avatar = ?, updated_at = ?
WHERE id = ?
RETURNING id, username, password_hash, nickname, avatar, auth_version, banned_at, last_login_at, created_at, updated_at
`

type SetUserAvatarParams struct {
	Avatar    sql.NullString `json:"avatar"`
	UpdatedAt int64          `json:"updated_at"`
	ID        int64          `json:"id"`
}

func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserAvatar, arg.Avatar, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.AuthVersion,
		&i.BannedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserBanned = `-- name: SetUserBanned :exec
UPDATE users
SET banned_at = ?, updated_at = ?
WHERE id = ?
`

type SetUserBannedParams struct {
	BannedAt  sql.NullInt64 `json:"banned_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        int64         `json:"id"`
}

func (q *Queries) SetUserBanned(ctx context.Context, arg SetUserBannedParams) error {
	_, err := q.db.ExecContext(ctx, setUserBanned, arg.BannedAt, arg.UpdatedAt, arg.ID)
	return err
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :exec
UPDATE users
SET password_hash = ?, auth_version = auth_version + 1, updated_at = ?
WHERE id = ?
`

type SetUserPasswordHashParams struct {
	PasswordHash string `json:"password_hash"`
	UpdatedAt    int64  `json:"updated_at"`
	ID           int64  `json:"id"`
}

func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, setUserPasswordHash, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}

const touchUserLastLogin = `-- name: TouchUserLastLogin :exec
UPDATE users
SET last_login_at = ?, updated_at = ?
WHERE id = ?
`

type TouchUserLastLoginParams struct {
	LastLoginAt sql.NullInt64 `json:"last_login_at"`
	UpdatedAt   int64         `json:"updated_at"`
	ID          int64         `json:"id"`
}

func (q *Queries) TouchUserLastLogin(ctx context.Context, arg TouchUserLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, touchUserLastLogin, arg.LastLoginAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserNickname = `-- name: UpdateUserNickname :one
UPDATE users
SET nickname = ?, updated_at = ?
WHERE id = ?
RETURNING id, username, password_hash, nickname, avatar, auth_version, banned_at, last_login_at, created_at, updated_at
`

type UpdateUserNicknameParams struct {
	Nickname  string `json:"nickname"`
	UpdatedAt int64  `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserNickname, arg.Nickname, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.AuthVersion,
		&i.BannedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
